language: java
install: ./gradlew assemble

before_script:
  - sudo hostname localhost
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6 mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
  - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo --version

script: ./gradlew check

notifications:
  recipients:
    - michaelklishin@me.com

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
services:
  - mongodb

cache:
  directories:
  - $HOME/.gradle